# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate autocorrelation at lag 9
#'
#' @param acfv \code{numeric} vector of autocorrelation values
#' @return \code{numeric} scalar
#' @references Hyndman R, Kang Y, Montero-Manso P, Talagala T, Wang E, Yang Y, O'Hara-Wild M (2022). _tsfeatures: Time Series Feature Extraction_. R package version 1.1, <https://CRAN.R-project.org/package=tsfeatures>.
#' @references B.D. Fulcher and N.S. Jones. hctsa: A computational framework for automated time-series phenotyping using massive feature extraction. Cell Systems 5, 527 (2017).
#' @references B.D. Fulcher, M.A. Little, N.S. Jones Highly comparative time-series analysis: the empirical structure of time series and their methods. J. Roy. Soc. Interface 10, 83 (2013).
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' ac_9(x)
#'
ac_9 <- function(acfv) {
    .Call('_CompEngineR_ac_9', PACKAGE = 'CompEngineR', acfv)
}

#' Converts an input vector into a binarized version from software package \code{hctsa}
#'
#' @param x \code{numeric} vector
#' @return \code{numeric} scalar
#' @references Hyndman R, Kang Y, Montero-Manso P, Talagala T, Wang E, Yang Y, O'Hara-Wild M (2022). _tsfeatures: Time Series Feature Extraction_. R package version 1.1, <https://CRAN.R-project.org/package=tsfeatures>.
#' @references B.D. Fulcher and N.S. Jones. hctsa: A computational framework for automated time-series phenotyping using massive feature extraction. Cell Systems 5, 527 (2017).
#' @references B.D. Fulcher, M.A. Little, N.S. Jones Highly comparative time-series analysis: the empirical structure of time series and their methods. J. Roy. Soc. Interface 10, 83 (2013).
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' binarize_mean(x)
#'
binarize_mean <- function(x) {
    .Call('_CompEngineR_binarize_mean', PACKAGE = 'CompEngineR', x)
}

#' Calculate points inside a given circular boundary in a 2-D embedding space from software package \code{hctsa}
#'
#' @param x \code{numeric} vector
#' @param acfv \code{numeric} vector of autocorrelation values
#' @param boundary \code{numeric} boundary for the circle calculation
#' @return \code{numeric} scalar
#' @references Hyndman R, Kang Y, Montero-Manso P, Talagala T, Wang E, Yang Y, O'Hara-Wild M (2022). _tsfeatures: Time Series Feature Extraction_. R package version 1.1, <https://CRAN.R-project.org/package=tsfeatures>.
#' @references B.D. Fulcher and N.S. Jones. hctsa: A computational framework for automated time-series phenotyping using massive feature extraction. Cell Systems 5, 527 (2017).
#' @references B.D. Fulcher, M.A. Little, N.S. Jones Highly comparative time-series analysis: the empirical structure of time series and their methods. J. Roy. Soc. Interface 10, 83 (2013).
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' embed2_incircle(x)
#'
embed2_incircle <- function(x, acfv, boundary = NA_real_) {
    .Call('_CompEngineR_embed2_incircle', PACKAGE = 'CompEngineR', x, acfv, boundary)
}

#' Calculates the entropy of a set of counts, \code{log(0)=0}
#'
#' @param x \code{numeric} vector
#' @return \code{numeric} scalar
#' @references Hyndman R, Kang Y, Montero-Manso P, Talagala T, Wang E, Yang Y, O'Hara-Wild M (2022). _tsfeatures: Time Series Feature Extraction_. R package version 1.1, <https://CRAN.R-project.org/package=tsfeatures>.
#' @references B.D. Fulcher and N.S. Jones. hctsa: A computational framework for automated time-series phenotyping using massive feature extraction. Cell Systems 5, 527 (2017).
#' @references B.D. Fulcher, M.A. Little, N.S. Jones Highly comparative time-series analysis: the empirical structure of time series and their methods. J. Roy. Soc. Interface 10, 83 (2013).
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' f_entropy(x)
#'
f_entropy <- function(x) {
    .Call('_CompEngineR_f_entropy', PACKAGE = 'CompEngineR', x)
}

#' Calculate coefficients and their standard error during linear regression and return the residuals as per \code{RcppArmadillo}
NULL

#' Calculate coefficients and their standard error during linear regression and return the residuals as per \code{RcppArmadillo}
#'
#' @param x \code{numeric} vector
#' @return \code{numeric} scalar
#' @references Dirk Eddelbuettel, Conrad Sanderson (2014). RcppArmadillo: Accelerating R with high-performance C++ linear algebra. Computational Statistics and Data Analysis, Volume 71, March 2014, pages 1054-1063. URL http://dx.doi.org/10.1016/j.csda.2013.02.005
#' @author Trent Henderson
#'
fastLmResid <- function(X, y) {
    .Call('_CompEngineR_fastLmResid', PACKAGE = 'CompEngineR', X, y)
}

fastLmResid2 <- function(X, y) {
    .Call('_CompEngineR_fastLmResid2', PACKAGE = 'CompEngineR', X, y)
}

#' Calculate time of first minimum in the autocorrelation function from software package \code{hctsa}
#'
#' @param x \code{numeric} vector
#' @param acfv \code{numeric} vector of autocorrelation values
#' @return \code{integer}
#' @references Hyndman R, Kang Y, Montero-Manso P, Talagala T, Wang E, Yang Y, O'Hara-Wild M (2022). _tsfeatures: Time Series Feature Extraction_. R package version 1.1, <https://CRAN.R-project.org/package=tsfeatures>.
#' @references B.D. Fulcher and N.S. Jones. hctsa: A computational framework for automated time-series phenotyping using massive feature extraction. Cell Systems 5, 527 (2017).
#' @references B.D. Fulcher, M.A. Little, N.S. Jones Highly comparative time-series analysis: the empirical structure of time series and their methods. J. Roy. Soc. Interface 10, 83 (2013).
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' firstmin_ac(x)
#'
firstmin_ac <- function(x, acfv) {
    .Call('_CompEngineR_firstmin_ac', PACKAGE = 'CompEngineR', x, acfv)
}

#' Calculate the first zero crossing of the autocorrelation function from software package \code{hctsa}
#'
#' @param x \code{numeric} vector
#' @param acfv \code{numeric} vector of autocorrelation values
#' @return \code{integer} scalar
#' @references Hyndman R, Kang Y, Montero-Manso P, Talagala T, Wang E, Yang Y, O'Hara-Wild M (2022). _tsfeatures: Time Series Feature Extraction_. R package version 1.1, <https://CRAN.R-project.org/package=tsfeatures>.
#' @references B.D. Fulcher and N.S. Jones. hctsa: A computational framework for automated time-series phenotyping using massive feature extraction. Cell Systems 5, 527 (2017).
#' @references B.D. Fulcher, M.A. Little, N.S. Jones Highly comparative time-series analysis: the empirical structure of time series and their methods. J. Roy. Soc. Interface 10, 83 (2013).
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' firstzero_ac(x)
#'
firstzero_ac <- function(x, acfv) {
    .Call('_CompEngineR_firstzero_ac', PACKAGE = 'CompEngineR', x, acfv)
}

#' Calculate fluctuation analysis from software package \code{hctsa}
#'
#' @importFrom stats lm residuals
#' @param x \code{numeric} vector
#' @return \code{numeric} scalar
#' @references Hyndman R, Kang Y, Montero-Manso P, Talagala T, Wang E, Yang Y, O'Hara-Wild M (2022). _tsfeatures: Time Series Feature Extraction_. R package version 1.1, <https://CRAN.R-project.org/package=tsfeatures>.
#' @references B.D. Fulcher and N.S. Jones. hctsa: A computational framework for automated time-series phenotyping using massive feature extraction. Cell Systems 5, 527 (2017).
#' @references B.D. Fulcher, M.A. Little, N.S. Jones Highly comparative time-series analysis: the empirical structure of time series and their methods. J. Roy. Soc. Interface 10, 83 (2013).
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' fluctanal_prop_r1(x)
#'
fluctanal_prop_r1 <- function(x) {
    .Call('_CompEngineR_fluctanal_prop_r1', PACKAGE = 'CompEngineR', x)
}

#' Calculate mode of a data vector from software package \code{hctsa}
#'
#' @param x \code{numeric} vector
#' @return \code{numeric} scalar
#' @references Hyndman R, Kang Y, Montero-Manso P, Talagala T, Wang E, Yang Y, O'Hara-Wild M (2022). _tsfeatures: Time Series Feature Extraction_. R package version 1.1, <https://CRAN.R-project.org/package=tsfeatures>.
#' @references B.D. Fulcher and N.S. Jones. hctsa: A computational framework for automated time-series phenotyping using massive feature extraction. Cell Systems 5, 527 (2017).
#' @references B.D. Fulcher, M.A. Little, N.S. Jones Highly comparative time-series analysis: the empirical structure of time series and their methods. J. Roy. Soc. Interface 10, 83 (2013).
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' histogram_mode(x)
#'
histogram_mode <- function(x, numBins = 10L) {
    .Call('_CompEngineR_histogram_mode', PACKAGE = 'CompEngineR', x, numBins)
}

#' Calculate the first zero crossing of the autocorrelation function of the residuals from Simple local time-series forecasting from software package \code{hctsa}
#'
#' @param x \code{numeric} vector
#' @param forecastMeth \code{character}
#' @return \code{integer} scalar
#' @references Hyndman R, Kang Y, Montero-Manso P, Talagala T, Wang E, Yang Y, O'Hara-Wild M (2022). _tsfeatures: Time Series Feature Extraction_. R package version 1.1, <https://CRAN.R-project.org/package=tsfeatures>.
#' @references B.D. Fulcher and N.S. Jones. hctsa: A computational framework for automated time-series phenotyping using massive feature extraction. Cell Systems 5, 527 (2017).
#' @references B.D. Fulcher, M.A. Little, N.S. Jones Highly comparative time-series analysis: the empirical structure of time series and their methods. J. Roy. Soc. Interface 10, 83 (2013).
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' localsimple_taures(x)
#'
localsimple_taures <- function(x, forecastMeth) {
    .Call('_CompEngineR_localsimple_taures', PACKAGE = 'CompEngineR', x, forecastMeth)
}

#' Calculate local motifs in a binary symbolization of the time series from software package \code{hctsa}
#'
#' @param x \code{numeric} vector
#' @return \code{numeric} scalar
#' @references Hyndman R, Kang Y, Montero-Manso P, Talagala T, Wang E, Yang Y, O'Hara-Wild M (2022). _tsfeatures: Time Series Feature Extraction_. R package version 1.1, <https://CRAN.R-project.org/package=tsfeatures>.
#' @references B.D. Fulcher and N.S. Jones. hctsa: A computational framework for automated time-series phenotyping using massive feature extraction. Cell Systems 5, 527 (2017).
#' @references B.D. Fulcher, M.A. Little, N.S. Jones Highly comparative time-series analysis: the empirical structure of time series and their methods. J. Roy. Soc. Interface 10, 83 (2013).
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' motiftwo_entro3(x)
#'
motiftwo_entro3 <- function(x) {
    .Call('_CompEngineR_motiftwo_entro3', PACKAGE = 'CompEngineR', x)
}

#' Calculate how the median depends on distributional outliers from software package \code{hctsa}
#'
#' @importFrom stats sd median
#' @param x \code{numeric} vector
#' @param zscored \code{Boolean} whether the data should be z-scored before computing the statistics. Defaults to \code{true}
#' @return \code{numeric} scalar
#' @references Hyndman R, Kang Y, Montero-Manso P, Talagala T, Wang E, Yang Y, O'Hara-Wild M (2022). _tsfeatures: Time Series Feature Extraction_. R package version 1.1, <https://CRAN.R-project.org/package=tsfeatures>.
#' @references B.D. Fulcher and N.S. Jones. hctsa: A computational framework for automated time-series phenotyping using massive feature extraction. Cell Systems 5, 527 (2017).
#' @references B.D. Fulcher, M.A. Little, N.S. Jones Highly comparative time-series analysis: the empirical structure of time series and their methods. J. Roy. Soc. Interface 10, 83 (2013).
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' outlierinclude_mdrmd(x)
#'
outlierinclude_mdrmd <- function(x, zscored = TRUE) {
    .Call('_CompEngineR_outlierinclude_mdrmd', PACKAGE = 'CompEngineR', x, zscored)
}

#' Calculate Second Sample Entropy of a time series from software package \code{hctsa}
#'
#' @param x \code{numeric} vector
#' @return \code{numeric} scalar
#' @references Hyndman R, Kang Y, Montero-Manso P, Talagala T, Wang E, Yang Y, O'Hara-Wild M (2022). _tsfeatures: Time Series Feature Extraction_. R package version 1.1, <https://CRAN.R-project.org/package=tsfeatures>.
#' @references B.D. Fulcher and N.S. Jones. hctsa: A computational framework for automated time-series phenotyping using massive feature extraction. Cell Systems 5, 527 (2017).
#' @references B.D. Fulcher, M.A. Little, N.S. Jones Highly comparative time-series analysis: the empirical structure of time series and their methods. J. Roy. Soc. Interface 10, 83 (2013).
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' sampen_first(x)
#'
sampen_first <- function(x) {
    .Call('_CompEngineR_sampen_first', PACKAGE = 'CompEngineR', x)
}

#' Calculate Second Sample Entropy from software package \code{hctsa}
#'
#' @param x \code{numeric} vector
#' @param M \code{integer} embedding dimension
#' @param r \code{numeric} threshold
#' @return \code{numeric} scalar
#' @references Hyndman R, Kang Y, Montero-Manso P, Talagala T, Wang E, Yang Y, O'Hara-Wild M (2022). _tsfeatures: Time Series Feature Extraction_. R package version 1.1, <https://CRAN.R-project.org/package=tsfeatures>.
#' @references B.D. Fulcher and N.S. Jones. hctsa: A computational framework for automated time-series phenotyping using massive feature extraction. Cell Systems 5, 527 (2017).
#' @references B.D. Fulcher, M.A. Little, N.S. Jones Highly comparative time-series analysis: the empirical structure of time series and their methods. J. Roy. Soc. Interface 10, 83 (2013).
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' sampenc(x, 6, 0.3)
#'
sampenc <- function(x, M = 6L, r = 0.3) {
    .Call('_CompEngineR_sampenc', PACKAGE = 'CompEngineR', x, M, r)
}

#' Calculate bootstrap-based stationarity measure from software package \code{hctsa}
#'
#' @param x \code{numeric} vector
#' @param l \code{integer} denoting the length of local time-series segments to analyse
#' @return \code{numeric} scalar
#' @references Hyndman R, Kang Y, Montero-Manso P, Talagala T, Wang E, Yang Y, O'Hara-Wild M (2022). _tsfeatures: Time Series Feature Extraction_. R package version 1.1, <https://CRAN.R-project.org/package=tsfeatures>.
#' @references B.D. Fulcher and N.S. Jones. hctsa: A computational framework for automated time-series phenotyping using massive feature extraction. Cell Systems 5, 527 (2017).
#' @references B.D. Fulcher, M.A. Little, N.S. Jones Highly comparative time-series analysis: the empirical structure of time series and their methods. J. Roy. Soc. Interface 10, 83 (2013).
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' spreadrandomlocal_meantaul(x)
#'
spreadrandomlocal_meantaul <- function(x, l = 50L) {
    .Call('_CompEngineR_spreadrandomlocal_meantaul', PACKAGE = 'CompEngineR', x, l)
}

#' Calculate standard deviation of the first derivative of the time series from software package \code{hctsa}
#'
#' @importFrom stats sd
#' @param x \code{numeric} vector
#' @return \code{numeric} scalar
#' @references Hyndman R, Kang Y, Montero-Manso P, Talagala T, Wang E, Yang Y, O'Hara-Wild M (2022). _tsfeatures: Time Series Feature Extraction_. R package version 1.1, <https://CRAN.R-project.org/package=tsfeatures>.
#' @references B.D. Fulcher and N.S. Jones. hctsa: A computational framework for automated time-series phenotyping using massive feature extraction. Cell Systems 5, 527 (2017).
#' @references B.D. Fulcher, M.A. Little, N.S. Jones Highly comparative time-series analysis: the empirical structure of time series and their methods. J. Roy. Soc. Interface 10, 83 (2013).
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' std1st_der(x)
#'
std1st_der <- function(x) {
    .Call('_CompEngineR_std1st_der', PACKAGE = 'CompEngineR', x)
}

#' Calculate normalized nonlinear autocorrelation, the numerator of the trev function of a time series from software package \code{hctsa}
#'
#' @param x \code{numeric} vector
#' @return \code{numeric} scalar
#' @references Hyndman R, Kang Y, Montero-Manso P, Talagala T, Wang E, Yang Y, O'Hara-Wild M (2022). _tsfeatures: Time Series Feature Extraction_. R package version 1.1, <https://CRAN.R-project.org/package=tsfeatures>.
#' @references B.D. Fulcher and N.S. Jones. hctsa: A computational framework for automated time-series phenotyping using massive feature extraction. Cell Systems 5, 527 (2017).
#' @references B.D. Fulcher, M.A. Little, N.S. Jones Highly comparative time-series analysis: the empirical structure of time series and their methods. J. Roy. Soc. Interface 10, 83 (2013).
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' trev_num(x)
#'
trev_num <- function(x) {
    .Call('_CompEngineR_trev_num', PACKAGE = 'CompEngineR', x)
}

#' Calculate a simulation of a hypothetical walker moving through the time domain from software package \code{hctsa}
#'
#' @param x \code{numeric} vector
#' @return \code{numeric} scalar
#' @references Hyndman R, Kang Y, Montero-Manso P, Talagala T, Wang E, Yang Y, O'Hara-Wild M (2022). _tsfeatures: Time Series Feature Extraction_. R package version 1.1, <https://CRAN.R-project.org/package=tsfeatures>.
#' @references B.D. Fulcher and N.S. Jones. hctsa: A computational framework for automated time-series phenotyping using massive feature extraction. Cell Systems 5, 527 (2017).
#' @references B.D. Fulcher, M.A. Little, N.S. Jones Highly comparative time-series analysis: the empirical structure of time series and their methods. J. Roy. Soc. Interface 10, 83 (2013).
#' @author Trent Henderson
#' @export
#' @examples
#' x <- rnorm(100)
#' walker_propcross(x)
#'
walker_propcross <- function(y) {
    .Call('_CompEngineR_walker_propcross', PACKAGE = 'CompEngineR', y)
}

